### ISSUE TITLE
FannyPack: What are the corner holes for?

### ISSUE THREAD

**Issue by gyscos** [DraftShift/CableManagement#1]
There's not a lot of guidance on how to assemble the FannyPack, so I'm not sure what to do with a set of holes in the design, near the 2 top corners.

![Screenshot From 2024-11-12 11-04-55](https://github.com/user-attachments/assets/95dd8d65-f133-47cc-927c-42653c899ad9)
![Screenshot From 2024-11-12 11-04-47](https://github.com/user-attachments/assets/23e60130-0241-4b21-bcc4-8db395c75cc0)

I can see the shallow holes meant for the magnets, but there is also a deeper hole in the corner.
It doesn't really look like it's for a screw, since there is no counterbore hole for the screw head. Is it for alignment?

EDIT: Ooh it looks like maybe we could put a heat insert in the base, and somehow screw the base onto something from the back, leaving the screw protruding a bit on the front, and the hole in the cover is to not interfere with that?

Wondering in which situation we could screw this base from behind.

**Comment by TheSin-** [comment]
nothing, was optional of later just ignore them for now.
